# Generated by Django 5.1.3 on 2024-11-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.TextField(default='Insert description here', max_length=500, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=None, verbose_name='Path'),
        ),
    ]
