# Generated by Django 5.1.3 on 2024-11-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_text_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
